### ISSUE TITLE
Error: Loading Resources after adding ContentBlocks field to content

### ISSUE THREAD

**Issue by hugopeek** [degoya/cb.resourceSelectInput#1]
Hi Alex,

Thanks for making this plugin, it's exactly what I was looking for! Unfortunately, I can't get it to work.. Getting an Error: Loading Resources or Error: contentblocks.error.no_resources message when trying to add the custom field. Creating the custom input type works fine.

Any ideas?

Greetings,
Hugo

**Comment by degoya** [comment]
Hello Hugo,

the Error contentblocks.error.no_resources  occurs when there are no resources loaded.

if you use the default settings for the input
Parent Resource ID to get Child list from = 0
Show only published Resources = 1
Show only searchable Resources = 1
make sure that your resource is publised and searchable. or just change those setting according to the resources you like to use.

if you still get problems let me know and i need to double check, but i got the default install working on several pages without any problems.

btw. i just work on V2 of the resource select with even more options and the posibillity to use filtering and where clause in the input option.

**Comment by hugopeek** [comment]
Hi Alex,

Thanks for the quick response! I double checked if the resources where published, searchable, and also tried with default setting (parent = 0), but keep getting the error.. I wanted to make a package first with GitPackageManagement, but also added the files manually on a different install to try it out..

Curious to try out V2 btw. I saw that you commented some lexicon lines out now, was planning on trying to fix those, so it'll be easy to add translations.. Are you working on that too by any chance, to prevent double work?

**Comment by degoya** [comment]
just pushed in the V2 in the repo, give it a try, i didn't added the lexicon support yet.

**Comment by hugopeek** [comment]
Ah cool, thanks!! Will give it a try next week!

**Comment by hugopeek** [comment]
Hi Alex,

Updated to v2, but still no luck unfortunately.. I am seeing some lines in the code that might be specific to your project though, after line 89 in the file `processors/search.class.php`:

```
        switch ($objectArray['template']) {
            case 8:
                $objectArray['templatelabel'] = ' ('.$objectArray['id'].') - (Quote)';
                break;
```

Is that related you think?

**Comment by degoya** [comment]
you are right, that was still some project specific stuff. i removed it but it should normaly work even with this code inside. this was only to show some aditional information to the resource by template.

you've setup the namespace, plugin event and still no result? 
maybe i'll find the time to build a package out of it for easier use.

**Comment by degoya** [comment]
Hello Hugo,

did you get the Input Type to work?

**Comment by hugopeek** [comment]
Hi Degoya,

Unfortunately, no.. Downloaded your latest, but still error: loading resources.

I see in resourceselect.input.js, that the input.loadResources function is empty.. Is that supposed to be like that? Not really much of a coder myself, so have no clue.. ;)

**Comment by hugopeek** [comment]
This is the error I get in the browser btw:

```
http://bootqamp-pkg.loc/assets/components/resourceselectinput/connector.php?action=search&query=&resource_where=&resource_context=0&resource_limit=4&resource_template=&contextkey=web&template=1&id=1&sortfield=pagetitle&sortorder=ASC&field=29
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by hugopeek** [comment]
Also, cannot delete the ContentBlock anymore in manager. More 404 responses there. Looks like the connector can't find the core elements or something..?

**Comment by Mark-H** [comment]
If the file exists at `http://bootqamp-pkg.loc/assets/components/resourceselectinput/connector.php`, you may have file permission issues somewhere in that tree

**Comment by hugopeek** [comment]
No, that's not it. Put everything on 777 to be sure, but no effect.
