### ISSUE TITLE
Missing Documentation: How to install

### ISSUE THREAD

**Issue by sonicpunk** [degoya/cb.resourceSelectInput#2]
I would love to be able to use this.  How can I install it?  And what MODX events need to be triggered by the plugin?

**Comment by degoya** [comment]
copy all the files in place. make a plugin with the content of resourceselectinput.plugin.php
and trigger to event ContentBlocks_RegisterInputs

**Comment by degoya** [comment]
added how to install to the readme

**Comment by sonicpunk** [comment]
Excellent!
