### ISSUE TITLE
Error Message while installing the package

### ISSUE THREAD

**Issue by patrickatwsrn** [degoya/cb.resourceSelectInput#7]
Got this error upon installing the package. 

```
Konsole läuft...
Versuche, das Package mit der Signatur resourceselectinput-2.0.0-pl zu installieren
Package gefunden... Bereite jetzt die Installation vor.
xPDOZip: Error opening archive at /home/buergerstiftung/public_html/core/packages/resourceselectinput-2.0.0-pl.transport.zip
PHP warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object
PHP warning: ZipArchive::close(): Invalid or uninitialized Zip object
Could not unpack package /home/buergerstiftung/public_html/core/packages/resourceselectinput-2.0.0-pl.transport.zip to /home/buergerstiftung/public_html/core/packages/. SIG: resourceselectinput-2.0.0-pl
Konnte das Package mit der Signatur "resourceselectinput-2.0.0-pl" nicht installieren.
```

Sounfs like the zip package is broken or the content is incomplete.

* No prior installs
* Skytoaster.com
* MODX 2.7.3
* Apache
* PHP 7.3.2

As far as I remember I have used this Custom CB before (thanks for sharing) and I didn't had issues.

**Comment by jdaehne** [comment]
Same for me!

![image](https://user-images.githubusercontent.com/10563227/90974024-c16f3f00-e527-11ea-80ba-7a0ef7df02b3.png)

![image](https://user-images.githubusercontent.com/10563227/90974031-ca601080-e527-11ea-88e6-3678c2419dc0.png)

**Comment by jdaehne** [comment]
I uploaded the transport package from your [package folder](https://github.com/degoya/cb.resourceSelectInput/tree/master/_packages) to my modx install and used that: That worked!

**Comment by degoya** [comment]
i've updated the package in the repo before, so it seems everything is fixed now. i'll close this issue.

**Comment by jdaehne** [comment]
Could you upload the package to the MODX Package-Provider? There is still the uninstallable version online. Thanx a lot.

**Comment by degoya** [comment]
you can find the new version here https://modx.com/extras/package/cb.resourceselectinputv2
